apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lxcfs-sidecar-injector
  labels:
    app: lxcfs-sidecar-injector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lxcfs-sidecar-injector
    spec:
      containers:
        - name: lxcfs-sidecar-injector
          image: lxcfs-sidecar-injector:latest
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/etc/webhook/certs/cert.pem
            - --tls-key-file=/etc/webhook/certs/key.pem
          ports:
            - containerPort: 443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: lxcfs-sidecar-injector-certs
