kind: Service
apiVersion: v1
metadata:
  name: lxcfs-sidecar-injector-svc
spec:
  selector:
    app: lxcfs-sidecar-injector
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
